<?php

namespace Container3YKSK8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I83v4AqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.I83v4Aq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.I83v4Aq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'postRepository' => ['privates', 'App\\Repository\\PostsRepository', 'getPostsRepositoryService', true],
            'subCategorie' => ['privates', '.errored..service_locator.I83v4Aq.App\\Entity\\SubCategories', NULL, 'Cannot autowire service ".service_locator.I83v4Aq": it references class "App\\Entity\\SubCategories" but no such service exists.'],
        ], [
            'postRepository' => 'App\\Repository\\PostsRepository',
            'subCategorie' => 'App\\Entity\\SubCategories',
        ]);
    }
}
