<?php

namespace Container3YKSK8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Wr6BzDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Wr_6BzD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Wr_6BzD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'imgService' => ['privates', 'App\\Service\\ImageService', 'getImageServiceService', true],
            'media' => ['privates', 'App\\Repository\\MediaRepository', 'getMediaRepositoryService', true],
        ], [
            'entityManager' => '?',
            'imgService' => 'App\\Service\\ImageService',
            'media' => 'App\\Repository\\MediaRepository',
        ]);
    }
}
