<?php

namespace Container3YKSK8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Mpa89RrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Mpa89Rr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Mpa89Rr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categorie' => ['privates', '.errored..service_locator.Mpa89Rr.App\\Entity\\Categories', NULL, 'Cannot autowire service ".service_locator.Mpa89Rr": it references class "App\\Entity\\Categories" but no such service exists.'],
            'postRepository' => ['privates', 'App\\Repository\\PostsRepository', 'getPostsRepositoryService', true],
        ], [
            'categorie' => 'App\\Entity\\Categories',
            'postRepository' => 'App\\Repository\\PostsRepository',
        ]);
    }
}
