<?php

namespace Container3YKSK8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPsysh_ConfigService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'psysh.config' shared service.
     *
     * @return \Psy\Configuration
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/psy/psysh/src/Configuration.php';

        $container->privates['psysh.config'] = $instance = new \Psy\Configuration();

        $instance->setHistoryFile(($container->targetDir.''.'/psysh_history'));

        return $instance;
    }
}
