<?php

namespace Container3YKSK8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSubCategories2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.zuxFTtn.App\Entity\SubCategories' shared service.
     *
     * @return \App\Entity\SubCategories
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.zuxFTtn": it references class "App\\Entity\\SubCategories" but no such service exists.');
    }
}
