<?php

namespace Container4DENHSF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPages2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.wCca7mC.App\Entity\Pages' shared service.
     *
     * @return \App\Entity\Pages
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.wCca7mC": it references class "App\\Entity\\Pages" but no such service exists.');
    }
}
