<?php

namespace Container4DENHSF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTwig_Markdown_DefaultService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'twig.markdown.default' shared service.
     *
     * @return \Twig\Extra\Markdown\DefaultMarkdown
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/twig/markdown-extra/src/MarkdownInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/twig/markdown-extra/src/DefaultMarkdown.php';

        return $container->privates['twig.markdown.default'] = new \Twig\Extra\Markdown\DefaultMarkdown();
    }
}
