<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTxMZHqF\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTxMZHqF/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerTxMZHqF.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerTxMZHqF\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerTxMZHqF\App_KernelProdContainer([
    'container.build_hash' => 'TxMZHqF',
    'container.build_id' => '1156d8bc',
    'container.build_time' => 1593642551,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTxMZHqF');
