<?php

namespace ContainerShpvg7F;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BdICVfaService extends App_KernelProdDebugContainer
{
    /**
     * Gets the private '.service_locator.bdICVfa' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bdICVfa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'commentsRepository' => ['privates', 'App\\Repository\\CommentsRepository', 'getCommentsRepositoryService', true],
        ], [
            'commentsRepository' => 'App\\Repository\\CommentsRepository',
        ]);
    }
}
