<?php

namespace ContainerShpvg7F;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MCsahEsService extends App_KernelProdDebugContainer
{
    /**
     * Gets the private '.service_locator.MCsahEs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MCsahEs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'post' => ['privates', '.errored..service_locator.MCsahEs.App\\Entity\\Posts', NULL, 'Cannot autowire service ".service_locator.MCsahEs": it references class "App\\Entity\\Posts" but no such service exists.'],
        ], [
            'post' => 'App\\Entity\\Posts',
        ]);
    }
}
