<?php

namespace ContainerShpvg7F;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContactService extends App_KernelProdDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.CSmT4oH.App\Entity\Contact' shared service.
     *
     * @return \App\Entity\Contact
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.CSmT4oH": it references class "App\\Entity\\Contact" but no such service exists.');
    }
}
