<?php

namespace ContainerFCZQFHI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZblMl8kService extends App_KernelProdDebugContainer
{
    /**
     * Gets the private '.service_locator.zblMl8k' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zblMl8k'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'commentRepo' => ['privates', 'App\\Repository\\CommentsRepository', 'getCommentsRepositoryService', true],
            'post' => ['privates', '.errored..service_locator.zblMl8k.App\\Entity\\Posts', NULL, 'Cannot autowire service ".service_locator.zblMl8k": it references class "App\\Entity\\Posts" but no such service exists.'],
            'postRepository' => ['privates', 'App\\Repository\\PostsRepository', 'getPostsRepositoryService', true],
        ], [
            'commentRepo' => 'App\\Repository\\CommentsRepository',
            'post' => 'App\\Entity\\Posts',
            'postRepository' => 'App\\Repository\\PostsRepository',
        ]);
    }
}
