<?php

namespace ContainerFCZQFHI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WCca7mCService extends App_KernelProdDebugContainer
{
    /**
     * Gets the private '.service_locator.wCca7mC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wCca7mC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'pageR' => ['privates', 'App\\Repository\\PagesRepository', 'getPagesRepositoryService', true],
            'post' => ['privates', '.errored..service_locator.wCca7mC.App\\Entity\\Pages', NULL, 'Cannot autowire service ".service_locator.wCca7mC": it references class "App\\Entity\\Pages" but no such service exists.'],
        ], [
            'pageR' => 'App\\Repository\\PagesRepository',
            'post' => 'App\\Entity\\Pages',
        ]);
    }
}
