<?php

namespace ContainerFCZQFHI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPosts2Service extends App_KernelProdDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.igxsez9.App\Entity\Posts' shared service.
     *
     * @return \App\Entity\Posts
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.igxsez9": it references class "App\\Entity\\Posts" but no such service exists.');
    }
}
