<?php

namespace ContainerRxju2AI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IcRxJr5Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.IcRxJr5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IcRxJr5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'img' => ['privates', 'App\\Repository\\MediaRepository', 'getMediaRepositoryService', true],
            'imgService' => ['privates', 'App\\Service\\ImageService', 'getImageServiceService', true],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'img' => 'App\\Repository\\MediaRepository',
            'imgService' => 'App\\Service\\ImageService',
            'manager' => '?',
        ]);
    }
}
