<?php

namespace ContainerRxju2AI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentsControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\CommentsController' shared autowired service.
     *
     * @return \App\Controller\CommentsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/CommentsController.php';

        $container->services['App\\Controller\\CommentsController'] = $instance = new \App\Controller\CommentsController();

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\CommentsController', $container));

        return $instance;
    }
}
