<?php

namespace ContainerRxju2AI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPagesService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.DSsnscE.App\Entity\Pages' shared service.
     *
     * @return \App\Entity\Pages
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.DSsnscE": it references class "App\\Entity\\Pages" but no such service exists.');
    }
}
