<?php

namespace ContainerRxju2AI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSubCategoriesService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.I83v4Aq.App\Entity\SubCategories' shared service.
     *
     * @return \App\Entity\SubCategories
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.I83v4Aq": it references class "App\\Entity\\SubCategories" but no such service exists.');
    }
}
