<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYKcwckl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYKcwckl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYKcwckl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYKcwckl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYKcwckl\App_KernelDevDebugContainer([
    'container.build_hash' => 'YKcwckl',
    'container.build_id' => '90c00d6c',
    'container.build_time' => 1593643036,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYKcwckl');
